# SITE CONFIGURATION
baseurl:
#"test_blog"
url: ""

# THEME-SPECIFIC CONFIGURATION
title: gcrNet                                    # site's title
description: "A website for UNCG community"      # used by search engines
avatar: assets/img/mainlogo.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: <code>gcrNet</code> developers <code>site</code> 
Welcome to the home of the Gate City Research Network (gcrNet), a multi-institutional Science-DMZ created by UNC Greensboro and North Carolina A&T State University for the purpose of supporting data intensive research. The gcrNet is supported by the National Science Foundation Office of Advanced CyberInfrastructure and is available to faculty at UNC Greensboro, NC A&T, and their research collaborators.

The gcrNet is designed to build upon the Science DMZ architecture developed by the Energy Sciences Network (ESnet) to meet the needs of high performance science applications in a network that is shared by multiple institutions.

The gcrNet operates under the governance of the Piedmont Regional Data Collaborative and the implementation project is funded by the National Science Foundation, award #1925623. # Change Blog header text
header_feature_image: assets/img/pexels/triangular.jpeg
avatar1: assets/img/UNCG-ITS-Logo.jpg 

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
katex: true                                             # Enable if using math markup
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
disqus_shortname:                                       # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  faq:
    output: true
  workshop: 
    output: true
  projects:
    output: true
  tutorials:
    output: true
  howto:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*", ".travis.yml",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
